### ISSUE TITLE
question

### ISSUE THREAD

**Issue by berrymot** [berrymot/canipa-ultlf#1]
@ultlang should the "last updated" thing be in actual time or stardates

**Comment by ultlang** [comment]
what are stardates lol

**Comment by ultlang** [comment]
also wait didn't i send the vocoid symbols to mb&b some time ago?

**Comment by berrymot** [comment]
> what are stardates lol

fancy star trek things. for example today at 9:57 am pacific daylight time is stardate `-302445.91`

> also wait didn't i

h.

**Comment by berrymot** [comment]
( @ultlang )

**Comment by ultlang** [comment]
ah i see. you can leave it as a stardate if you want ig it's okay

**Comment by berrymot** [comment]
alr
