### ISSUE TITLE
prevelarized bilabial nasal

### ISSUE THREAD

**Issue by berrymot** [berrymot/canipa-ultlf#3]
![](https://user-images.githubusercontent.com/50974538/121818935-3ccce900-cc3f-11eb-9675-b77a1710ed02.jpeg)

ahhh

**Comment by berrymot** [comment]
[le ping] @ultlang

**Comment by ultlang** [comment]
![Untitled180_20210613212036](https://user-images.githubusercontent.com/50134925/121819406-3a917b80-cc8d-11eb-8d8f-01fd63b2aaa9.png)
maybe like this for <n ŋ [ŋ with loop] [whatever this is]>?

**Comment by ultlang** [comment]
![Untitled180_20210613212251](https://user-images.githubusercontent.com/50134925/121819472-87755200-cc8d-11eb-8a3a-c5781b665f9e.png)
or maybe like this? idk

**Comment by berrymot** [comment]
it's meant to be <m> with a middle bottom loop thingy

**Comment by berrymot** [comment]
and i kinda don't want to make it 7 pixels wide so

**Comment by ultlang** [comment]
ah like this then ig? idk #
![Untitled180_20210613213329](https://user-images.githubusercontent.com/50134925/121819738-0c14a000-cc8f-11eb-938e-6add9d590081.png)

**Comment by ultlang** [comment]
that looks a bit odd unfortunately

**Comment by berrymot** [comment]
yeah idk either

i *could* do that but with the loop 1px lower and it'd look ok i thikn
